apiVersion: v2
name: murano
description: A Helm chart for murano
type: application
version: 2.4.1
appVersion: 14.0.0-7-g6b68cd16-8-5
sources:
- https://github.com/NeCTAR-RC/murano-helm.git
dependencies:
- name: nectarlib
  version: 4.3.0
  repository: oci://registry.rc.nectar.org.au/nectar-helm
