# Default values for murano.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


conf:
  debug: false
  admin_role: Admin
  transport_url:
  keystone:
    auth_url:
    username: murano
    project_name: service
    memcached_servers: []
  rabbitmq:
    host:
    port: 5671
    login: murano
    virtual_host: murano
  murano:
    url:

vault:
  role: k8s
  settings_secret: 'path/to/secret/in/vault'

api:
  port: 8082
  command:
    - kolla_httpd_start
  apache:
    enabled: true
    wsgi_script: murano-wsgi-api
  image:
    repository: registry.rc.nectar.org.au/kolla/ubuntu-source-murano-api
  replicaCount: 1
  pdb:
    enabled: false
    minAvailable: 1
  podAffinityPreset: ""
  podAntiAffinityPreset: soft
  nodeAffinityPreset:
    type: ""
    key: ""
    values: []
  affinity: {}
  resources: {}
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

engine:
  name: engine
  command:
    - murano-engine
  image:
    repository: registry.rc.nectar.org.au/kolla/ubuntu-source-murano-engine
  replicaCount: 1
  pdb:
    enabled: false
    minAvailable: 1
  podAffinityPreset: ""
  podAntiAffinityPreset: soft
  nodeAffinityPreset:
    type: ""
    key: ""
    values: []
  affinity: {}
  resources: {}
  volumes:
    - name: var-tmp
      emptyDir: {}
  volume_mounts:
    - name: var-tmp
      mountPath: /var/tmp/

job:
  db_sync:
    enabled: true
    command:
      - murano-db-manage
      - --config-file
      - /etc/murano/murano.conf
      - --config-file
      - /etc/murano/murano.conf.d/secrets.conf
      - upgrade

oslo_policy:

image:
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "1"
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 42433
  runAsGroup: 42433
  fsGroup: 42433
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL
    add:
      - NET_BIND_SERVICE

# capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: NodePort

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local


autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []
